# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 06:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brothers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(default=0)),
                ('comments', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('broid', models.IntegerField(default=0)),
                ('comment', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rushee',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('first', models.CharField(db_index=True, max_length=100)),
                ('last', models.CharField(db_index=True, max_length=100)),
                ('netid', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('build', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('latest_signin', models.IntegerField(default=0)),
                ('latest_signin_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('name', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False)),
                ('char', models.CharField(default='', max_length=100)),
                ('val', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signin',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('qotd', models.CharField(default='', max_length=100)),
                ('ans', models.CharField(default='', max_length=200)),
                ('img', models.ImageField(default='/static/rush/no_img.jpeg', upload_to='rush_pics/')),
                ('img_small', models.ImageField(default='/static/rush/no_img.jpeg', upload_to='rush_pics_small/')),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rush.Rushee')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='rid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rush.Rushee'),
        ),
        migrations.AddField(
            model_name='comment',
            name='rid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rush.Rushee'),
        ),
    ]
