# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-26 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0010_auto_20170119_1405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rushee',
            options={'ordering': ('last',)},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'ordering': ('name',)},
        ),
    ]
