# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-02-19 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0011_auto_20190426_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='char',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='setting',
            name='val',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
