# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brothers',
            fields=[
                ('id', models.AutoField(db_index=True, max_length=4, primary_key=True, serialize=False)),
                ('first', models.CharField(db_index=True, default='', max_length=100)),
                ('last', models.CharField(db_index=True, default='', max_length=100)),
                ('major', models.TextField(default='', max_length=100)),
                ('home', models.TextField(default='', max_length=100)),
                ('year', models.IntegerField(default='1909')),
                ('pic', models.ImageField(default='main/img/brothers/no_img.jpeg', upload_to=b'')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Officers',
            fields=[
                ('id', models.AutoField(db_index=True, max_length=4, primary_key=True, serialize=False)),
                ('position', models.TextField(default='', max_length=100)),
                ('name', models.TextField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=75)),
                ('year', models.IntegerField(default='1909')),
            ],
        ),
    ]
